### PR TITLE
fixed redirect bug

### LINKED ISSUE #126: UserManager - Fix RedirectURI when deleting a user
Redirect to logout only when someone delete himself - otherwise just return to the list of users

### LINKED ISSUE #127: Edit Manage Users bug
after there is an error in submission, not showing roles

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by bsuro10** [comment]
If you can't delete admin you can never delete yourself 
Plus you have the permission to change roles so you can delete an admin by changing him to author or client - lets do that an admin can delete everyone but himself

**Review by bsuro10 — CHANGES_REQUESTED** [review]
- [x] If you can't delete admin you can never delete yourself
Plus you have the permission to change roles so you can delete an admin by changing him to author or client - lets do that an admin can delete everyone but himself

- [x] Make that admins can not change their own roles because if an admin changes his role to Client he still has admin privileged since the cookies save his `admin` role. 
Do it by adding new condition in UserController line 454:
if ((!RoleChanged) || (userId.Equals(id.ToString()))

**Comment by ghost** [comment]
> If you can't delete admin you can never delete yourself.

You can delete admin only if it's you, there is a check for it

**Comment by bsuro10** [comment]
> > If you can't delete admin you can never delete yourself.
> 
> You can delete admin only if it's you, there is a check for it

Nice

**Comment by ghost** [comment]
I changed it so Admins can't change role for admins in both sides, client and server. Except when the admin is the user that is trying to change. (After change - auto logout)
Also I have made the delete option to not be seen for admin users except the Admin current user himself.
And i fixed the bug of the role options on the way.

**Review by bsuro10 — APPROVED** [review]
Good job!

**Review by barBen — APPROVED** [review]

**Pull request merged**
